app: stop pinging blocklisted users
storj/changesetchihuahua pull request #2
Opened 2022-08-02 14:32 UTC by Erikvv

I am on the blocklisted users but I'm still getting pings. This
hopefully fixes that. Not tested.

2022-08-07 20:48 UTC, thepaul requested changes
This changes the semantics of the `blocklist-ids` config item, so it would be nice to update the comment on that as well (line 79 should say something like "comma-separated list of chat IDs of users to avoid messaging *or pinging*").

2022-08-07 20:48 UTC, thepaul commented on app/core.go
> +		return chatID
`chatID` will be a string like `"U037Q3NGS9B"`, which will be unhelpful to the average reader. We should return `account.DisplayName()` instead.

2022-09-21 21:50 UTC, Erikvv commented
Maybe you can explain better what this tool can help me with so maybe I don't have to go for a full mute but constomize it otherwise.

I am on the blocklist but I remember I mainly asked it to stop these 5 PM pings which I don't want because I'm acutely aware of all the open changes anyways. 

I had hoped to rely on notifications for github and e-mail filters for gerrit. But the github notifications are just too much because I get everything from all teams, and protonmail's e-mail filters are too limited. So I am just overwhelmed and it has all become pretty useless...

2022-10-22 09:18 UTC, Erikvv commented
We aren't using this tool currently so I'm shelving this.

2022-10-22 09:18 UTC, closed without merging